<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OvoUi\OvoUi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controls\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    </ItemGroup>

</Project>
