<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="12.1.3" />
      <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\" />
      <Folder Include="Theme\Animations\" />
    </ItemGroup>
    
    <ItemGroup>
      <AvaloniaResource Include="Assets\**"/>
      <EmbeddedResource Include="..\..\assets\iconfont.ttf">
        <Link>Assets\iconfont.ttf</Link>
      </EmbeddedResource>
      <EmbeddedResource Include="..\..\assets\AlimamaFangYuanTi-Regular.ttf">
        <Link>Assets\AlimamaFangYuanTi-Regular.ttf</Link>
      </EmbeddedResource>
      <EmbeddedResource Include="..\..\assets\AlimamaFangYuanTi-Bold.ttf">
        <Link>Assets\AlimamaFangYuanTi-Bold.ttf</Link>
      </EmbeddedResource>
    </ItemGroup>    
    

</Project>
