<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>OvoUi.Demo</RootNamespace>
        <AssemblyName>OvoUi.Demo</AssemblyName>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <Title>OvoUi Demo</Title>
        <Description>Cross-platform demonstration application for OvoUi.</Description>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageReference Include="HotAvalonia" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\OvoUi\OvoUi.csproj"/>
        <ProjectReference Include="..\..\OvoUi.Fonts\OvoUi.Fonts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="..\..\..\assets\icon.ico">
            <Link>Assets\icon.ico</Link>
        </AvaloniaResource>
        <AvaloniaResource Include="..\..\..\assets\icon_256.png">
            <Link>Assets\icon_256.png</Link>
        </AvaloniaResource>
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Pages\OverviewPage.axaml" />
    </ItemGroup>
</Project>
