<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <AdditionalFiles Include="$(MSBuildProjectDirectory)\**\*.xaml;$(MSBuildProjectDirectory)\**\*.axaml"
                         Exclude="$(MSBuildProjectDirectory)\bin\**;$(MSBuildProjectDirectory)\obj\**" />
    </ItemGroup>
</Project>
